version: '3.8'
services:
    reverse_proxy:
        build:
            context: ./conf/nginx
            dockerfile: Dockerfile
            args:
                - TIME_ZONE=${TIME_ZONE}
                - LANG_NAME=${LANG_NAME}
                - LANG_INPUTFILE=${LANG_INPUTFILE}
                - LANG_CHARMAP=${LANG_CHARMAP}
        image: hoshisakan/nginx:1.23.3
        container_name: nginx-dev
        environment:
          - LANG=${LANG_NAME}
        volumes:
            - ./web/temp/dist/index.html:/web/dist/index.html
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./web/mvc/deploy/certs:/etc/nginx/ssl
            - ./logs/nginx:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - postgres_db
            - web_1
        networks:
            - ${EXTERNAL_NETWORK}
        user: root
        tty: true
        restart: always

    web_1:
      build:
          context: ./conf/dotnet/6.0/web_1
          dockerfile: Dockerfile
          args:
              - DOTNET_VERSION=${DOTNET_VERSION}
              - TIME_ZONE=${TIME_ZONE}
              - LANG_NAME=${LANG_NAME}
              - LANG_INPUTFILE=${LANG_INPUTFILE}
              - LANG_CHARMAP=${LANG_CHARMAP}
      image: hoshisakan/web_1/dotnet:6.0
      container_name: web-1-dev
      environment:
          - LANG=${LANG_NAME}
      volumes:
          - ./web/mvc/HoshiBook:/app
          - ./web/mvc/deploy/HoshiBookWeb:/deploy/HoshiBookWeb
          - ./web/mvc/deploy/certs:/deploy/certs
      expose:
        - 5002
        - 7232
      depends_on:
        - postgres_db
      networks:
          - ${EXTERNAL_NETWORK}
      tty: true
      restart: always

    postgres_db:
        build:
            context: ./conf/postgresql
            dockerfile: Dockerfile
            args:
                - TIME_ZONE=${TIME_ZONE}
                - LANG_NAME=${LANG_NAME}
                - LANG_INPUTFILE=${LANG_INPUTFILE}
                - LANG_CHARMAP=${LANG_CHARMAP}
        image: hoshisakan/postgresql:15.2
        container_name: postgresql-dev
        environment:
            - DATABASE_HOST=${DATABASE_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data
            - TZ=${TIME_ZONE}
            - LANG=${LANG_NAME}
        volumes:
            - ./data/postgresql/pgdata:/var/lib/postgresql/data
            - ./data/postgresql/pgdata_backup:/pgdata_backup
        ports:
            - 5432:5432
        networks:
            - ${EXTERNAL_NETWORK}
        restart: always

    pgadmin:
        build: ./conf/postgresql_admin
        image: hoshisakan/pgadmin:6.20
        container_name: postgresql-admin-dev
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-test@test.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-test123!}
            - LANG=${LANG_NAME}
        volumes:
            - pgadmin:/var/lib/pgadmin
            - ./data/pgadmin/pgadmin_data:/var/lib/pgadmin
        ports:
            - 5433:80
        depends_on:
            - postgres_db
        networks:
            - ${EXTERNAL_NETWORK}
        user: root
        restart: always

networks:
    common-bridge:
        external: true

volumes:
    pgadmin: